#!/usr/bin/env bash

#Markup vars. We don't want to sit writing the same stuff over and over, don't we? ;)

SEP=" "
SEP1="-"
BG="background-color:transparent"
DIVHEADER="<table valign=\"middle\" cellspacing=\"0\" cellpadding=\"0\" style=\"${BG}\"><tr>"

#Check for parameters ($1 be the actually $2 for the applet script)

if [[ "$1" = "mpc" ]]; then

  PLAY="<a href=\"exec:mpc toggle\"><img src=\"$THEMEDIR/BottomPanel/play.png\"width=\"16\"></a>"
  PAUSE="<a href=\"exec:mpc toggle\"><img src=\"$THEMEDIR/BottomPanel/pause.png\"width=\"16\"></a>"
  STOP="<a href=\"exec:cantata\"><img src=\"$THEMEDIR/BottomPanel/stop.png\"width=\"16\"></a>"
  
  out1="$DIVHEADER<td>$PLAY</td><td>$SEP</td><td>$SEP</td><td>$SEP</td><td>$SEP</td><td>$TITLE</td><td>$SEP</td><td>$SEP1</td><td>$SEP</td><td>$ARTIST</td></tr></table>"

  out2="$DIVHEADER<td>$PAUSE</td><td>$SEP</td><td>$SEP</td><td>$SEP</td><td>$SEP</td><td>$ALBUM</td><td>$SEP</td><td>$SEP1</td><td>$SEP</td><td>$ARTIST</td></tr></table>"

  out3="$DIVHEADER$STOP</tr></table>"

elif [[ "$1" = "cover" ]]; then

  COV="<a href=\"exec:mpc toggle\"><img src=\"$HOME/immagini/cover/$ALBUM\"width=\"40\" /></a>"
  NOCOV="<a href=\"exec:cantata\"><img src=\"$confDir/Themes/Eve/BottomPanel/google-musicmanager.svg\"width=\"45\" /></a>"

  out1="$DIVHEADER$COV</tr></table>"

  out2="$DIVHEADER$COV</tr></table>"

  out3="$DIVHEADER$NOCOV</tr></table>"

fi

if [[ "$STS" = "playing" ]]; then
    echo "$out1"
elif [[ "$STS" = "paused" ]]; then
    echo "$out2"
else
    echo "$out3"  
fi