#!/usr/bin/env bash

BAK="<a href=\"exec:/usr/bin/bash $HOME/.local/share/Scripts/backup_manager\"><img src=\"$THEMEDIR/TopPanel/backup.png\"width=\"18\"></a>"
NOBAK="<a href=\"exec:konsole --hold -e echo \'No backup directory found\'\"><img src=\"$THEMEDIR/TopPanel/backup.png\"width=\"18\"></a>"

if [[ -d "$DIR" ]]; then
    
  echo "$BAK"
    
else

  echo "$NOBAK"

fi